version: '3.4'
    
services:
  proxy:
    build:
      args:
        SP_METADATA_URL: http://host.docker.internal/saml2/metadata
        IDP_METADATA_URL: http://host.docker.internal:8080/metadata.xml
        #IDP_METADATA_URL: http://host.docker.internal:8088/metadata
      context: ./
      dockerfile: ./Dockerfile
    image: satosa_proxy 
    container_name: saml2spid
    ports:
      - 10000:10000
      - 9999:9999
      - 4444:4444
    working_dir: /satosa_proxy
    #COPY example/ $BASEDIR/
    volumes:
      - ./example/static:/satosa_proxy/static
      - ./example/attributes-map:/satosa_proxy/attributes-map
      - ./example/backends:/satosa_proxy/backends
      - ./example/plugins:/satosa_proxy/plugins
      - ./example/plugins/internal_attributes.xml:/satosa_proxy/plugins/internal_attributes.xml
      - ./example/plugins/proxy_conf.xml:/satosa_proxy/plugins/proxy_conf.xml
     # - ./satosa:/usr/lib/python3.8/site-packages/satosa
    stdin_open: true
    tty: true
    command:
      bash -c "./demo-run.sh"
    networks:
      - app-network

  # spidtest:
  #   build:
  #     context: ../spid-testenv2
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 8088:8088
  #   volumes:
  #     - ../spid-testenv2/conf:/app/conf
  #   working_dir: /app
  #   command:
  #     bash -c "python ./spid-testenv.py"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

    